networks:
  transcendence:
    name: transcendence
    driver: bridge


services:
  auth_db:
    image: postgres:13
    container_name: auth_db
    env_file:
      - .env.auth
    ports:
      - "5432:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    depends_on:
      - vault
    networks:
      - transcendence

  auth-service:
    build: ./backend/auth_service
    container_name: auth-service
    image: auth-service
    ports:
      - "8000:8000"
    env_file:
      - .env.auth
    depends_on:
      vault:
        condition: service_healthy
        restart: true
      auth_db:
        condition: service_started
    volumes:
      - ./vault/django/auth_service:/vault/django/auth_service
    networks:
      - transcendence

#  game_db:
#    image: postgres:13
#    container_name: game_db
#    env_file:
#      - .env.game
#    ports:
#      - "5433:5432"
#    volumes:
#      - game_postgres_data:/var/lib/postgresql/data
#    networks:
#      - transcendence
#
#  game-service:
#    build: ./backend/game_service
#    container_name: game-service
#    image: game-service
#    ports:
#      - "8001:8001"
#    env_file:
#      - .env.game
#    volumes:
#      - ./vault/django/game_service:/vault/django/game_service
#    depends_on:
#      - game_db
#    networks:
#      - transcendence

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    env_file:
      - .env
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl/:ro
      - ./frontend:/var/www/transcendence:ro
    networks:
      - transcendence

  vault:
    build: ./vault/.
    container_name: vault
    ports:
      - "8200:8200"
      - "8201:8201"
    cap_add:
      - IPC_LOCK
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8200/v1/sys/health | grep -E '\"sealed\":false,\"initialized\":true' || exit 1"]
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 5s
    volumes:
      - ./vault/vault_config:/vault/vault_config
      - ./vault/data:/vault/file
      - ./vault/keys:/vault/keys
      - ./vault/django/auth_service:/vault/django/auth_service
      # - ./vault/django/game_service:/vault/django/game_service
    networks:
      - transcendence

volumes:
  auth_postgres_data:
  game_postgres_data:
  vault_data:
