networks:
  transcendence:
    name: transcendence
    driver: bridge


services:
  auth_db:
    image: postgres:13
    container_name: auth_db
    env_file:
      - .env.auth
    ports:
      - "5432:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    networks:
      - transcendence
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mfa_db:
    image: postgres:13
    container_name: mfa_db
    restart: always
    env_file:
      - .env.mfa
    volumes:
      - mfa_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - transcendence
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build: ./backend/auth_service
    container_name: auth-service
    image: auth-service
    ports:
      - "8000:8000"
    env_file:
      - .env.auth
    depends_on:
      auth_db:
        condition: service_healthy
    networks:
      - transcendence

  mfa-service:
    build: ./backend/mfa_service
    container_name: mfa-service
    image: mfa-service
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      mfa_db:
        condition: service_healthy
    env_file:
      - .env.mfa
    networks:
      - transcendence

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl/:ro
      - ./frontend:/var/www/transcendence:ro
    networks:
      - transcendence

volumes:
  auth_postgres_data:
  game_postgres_data:
  mfa_postgres_data:
