networks:
  transcendence:
    name: transcendence
    driver: bridge


services:
  db:
    image: postgres:13
    container_name: postgreSQL
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - transcendence

  auth_service:
    build: ./backend/auth_service
    container_name: auth_service
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - transcendence

volumes:
  postgres_data: