networks:
  transcendence:
    name: transcendence
    driver: bridge


services:
  db:
    image: postgres:13
    container_name: postgreSQL
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - transcendence

  auth_service:
    build: ./backend/auth_service
    container_name: auth_service
    image: auth_service
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - transcendence

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl/:ro
      - ./frontend:/var/www/transcendence:ro
    networks:
      - transcendence
    

volumes:
  postgres_data:

# docker exec -it auth_service python manage.py migrate
# docker exec -it postgreSQL psql -U admin -d transcendence 