networks:
  transcendence:
    name: transcendence
    driver: bridge


services:
  auth_db:
    image: postgres:13
    container_name: auth_db
    env_file:
      - .env.auth
    ports:
      - "5432:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    networks:
      - transcendence

  auth_service:
    build: ./backend/auth_service
    container_name: auth_service
    image: auth_service
    ports:
      - "8000:8000"
    env_file:
      - .env.auth
    depends_on:
      - auth_db
    networks:
      - transcendence

  game_db:
    image: postgres:13
    container_name: game_db
    env_file:
      - .env.game
    ports:
      - "5433:5432"
    volumes:
      - game_postgres_data:/var/lib/postgresql/data
    networks:
      - transcendence

  game_service:
    build: ./backend/game_service
    container_name: game_service
    image: game_service
    ports:
      - "8001:8001"
    env_file:
      - .env.game
    depends_on:
      - game_db
    networks:
      - transcendence

#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    ports:
#      - "443:443"
#      - "80:80"
#    env_file:
#      - .env
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./nginx/ssl:/etc/nginx/ssl/:ro
#      - ./frontend:/var/www/transcendence:ro
#    networks:
#      - transcendence

volumes:
  auth_postgres_data:
  game_postgres_data:
