groups:
  - name: container_alerts
    rules:
      - alert: nginxDown
        expr: container_last_seen{container_label_com_docker_compose_service="nginx"}
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Container Down"
          description: "Container {{ $labels.container_name }} is no longer running."
      - alert: grafanaDown
        expr: container_last_seen{container_label_com_docker_compose_service="grafana"}

        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Container Down"
          description: "Container {{ $labels.container_name }} is no longer running."
      
      - alert: HighCPU  Usage
        expr: rate(container_cpu_usage_seconds_total{container_name!=""}[2m]) > 0.9
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High CPU Usage"
          description: "Container {{ $labels.container_name }} is using high CPU."

      - alert: HighMemoryUsage
        expr: container_memory_working_set_bytes{container_name!=""} > 500000000
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High Memory Usage"
          description: "Container {{ $labels.container_name }} is using excessive memory."