# Generated by Django 5.0.6 on 2024-11-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('player1_username', models.CharField(max_length=200)),
                ('player2_username', models.CharField(max_length=200)),
                ('winner', models.CharField(max_length=200)),
                ('player1_score', models.IntegerField()),
                ('player2_score', models.IntegerField()),
                ('duration', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
