# Generated by Django 5.0.6 on 2024-11-22 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='duration',
        ),
    ]
